const config = {
  locales: [
    'ru',
    'en',
  ],
  translations: {
    ru: {
      "Analytics": "Аналитика",
      "Auth.components.Oops.text": "Ваш аккаунт был заблокирован.",
      "Auth.components.Oops.text.admin": "Если это ошибка, пожалуйста, свяжитесь с администратором.",
      "Auth.components.Oops.title": "Упс...",
      "Auth.form.active.label": "Активный",
      "Auth.form.button.forgot-password": "Отправить email",
      "Auth.form.button.go-home": "ВЕРНУТЬСЯ НА ГЛАВНУЮ",
      "Auth.form.button.login": "Войти",
      "Auth.form.button.login.providers.error": "Мы не можем подключить вас через выбранного провайдера.",
      "Auth.form.button.login.strapi": "Войти через Strapi",
      "Auth.form.button.password-recovery": "Восстановление пароля",
      "Auth.form.button.register": "Начнем",
      "Auth.form.confirmPassword.label": "Подтверждение пароля",
      "Auth.form.currentPassword.label": "Текущий пароль",
      "Auth.form.email.label": "Email",
      "Auth.form.email.placeholder": "например, kai@doe.com",
      "Auth.form.error.blocked": "Ваш аккаунт был заблокирован администратором.",
      "Auth.form.error.code.provide": "Указан неверный код.",
      "Auth.form.error.confirmed": "Ваш email не подтвержден.",
      "Auth.form.error.email.invalid": "Некорректный email.",
      "Auth.form.error.email.provide": "Пожалуйста, укажите имя пользователя или email.",
      "Auth.form.error.email.taken": "Этот email уже используется.",
      "Auth.form.error.invalid": "Неверный идентификатор или пароль.",
      "Auth.form.error.params.provide": "Указаны неверные параметры.",
      "Auth.form.error.password.format": "Ваш пароль не может содержать символ `$` более трех раз.",
      "Auth.form.error.password.local": "Этот пользователь никогда не устанавливал локальный пароль, пожалуйста, войдите через провайдера, использованного при создании аккаунта.",
      "Auth.form.error.password.matching": "Пароли не совпадают.",
      "Auth.form.error.password.provide": "Пожалуйста, введите пароль.",
      "Auth.form.error.ratelimit": "Слишком много попыток, попробуйте снова через минуту.",
      "Auth.form.error.user.not-exist": "Такого email не существует.",
      "Auth.form.error.username.taken": "Имя пользователя уже занято.",
      "Auth.form.firstname.label": "Имя",
      "Auth.form.firstname.placeholder": "например, Кай",
      "Auth.form.forgot-password.email.label": "Введите ваш email",
      "Auth.form.forgot-password.email.label.success": "Email успешно отправлен на",
      "Auth.form.lastname.label": "Фамилия",
      "Auth.form.lastname.placeholder": "например, Доу",
      "Auth.form.password.hide-password": "Скрыть пароль",
      "Auth.form.password.hint": "Минимум 8 символов, 1 заглавная буква, 1 строчная буква и 1 цифра",
      "Auth.form.password.show-password": "Показать пароль",
      "Auth.form.register.news.label": "Оставаться в курсе новых функций и улучшений (при этом вы принимаете {terms} и {policy}).",
      "Auth.form.register.subtitle": "Учетные данные используются только для аутентификации в Strapi. Все сохраненные данные будут храниться в вашей базе данных.",
      "Auth.form.rememberMe.label": "Запомнить меня",
      "Auth.form.username.label": "Имя пользователя",
      "Auth.form.username.placeholder": "например, Kai_Doe",
      "Auth.form.welcome.subtitle": "Войдите в ваш аккаунт Strapi",
      "Auth.form.welcome.title": "Добро пожаловать в Strapi!",
      "Auth.link.forgot-password": "Забыли пароль?",
      "Auth.link.ready": "Готовы войти?",
      "Auth.link.signin": "Войти",
      "Auth.link.signin.account": "Уже есть аккаунт?",
      "Auth.login.sso.divider": "Или войдите с помощью",
      "Auth.login.sso.loading": "Загрузка провайдеров...",
      "Auth.login.sso.subtitle": "Войдите в свой аккаунт через SSO",
      "Auth.privacy-policy-agreement.policy": "политика конфиденциальности",
      "Auth.privacy-policy-agreement.terms": "условия",
      "Auth.reset-password.title": "Сброс пароля",
      "Content Manager": "Контент-менеджер",
      "Content Type Builder": "Конструктор типов контента",
      "Documentation": "Документация",
      "Email": "Email",
      "Files Upload": "Загрузка файлов",
      "HomePage.head.title": "Главная страница",
      "HomePage.header.subtitle": "Добро пожаловать в вашу панель администрирования",
      "HomePage.header.title": "Привет, {name}",
      "HomePage.helmet.title": "Главная страница",
      "HomePage.roadmap": "Посмотрите наш план развития",
      "HomePage.welcome.congrats": "Поздравляем!",
      "HomePage.welcome.congrats.content": "Вы вошли в систему как первый администратор. Чтобы познакомиться с мощными функциями Strapi,",
      "HomePage.welcome.congrats.content.bold": "мы рекомендуем создать ваш первый Collection-Type.",
      "HomePage.widget.error": "Не удалось загрузить содержимое виджета.",
      "HomePage.widget.loading": "Загрузка содержимого виджета",
      "HomePage.widget.no-data": "Контент не найден.",
      "Homepage.cloudBox.buttonText": "Развернуть в Strapi Cloud",
      "Homepage.cloudBox.subTitle": "Используйте оптимизированный стек Strapi, включающий базу данных, провайдера email и CDN.",
      "Homepage.cloudBox.title": "Развертывание в Strapi Cloud",
      "Homepage.githubBox.buttonText": "Загрузить на GitHub",
      "Homepage.githubBox.subTitle.not-versioned": "Ваш проект должен быть загружен в GitHub перед развертыванием в Strapi Cloud.",
      "Homepage.githubBox.subTitle.versioned": "Вы сделали это! Остался всего один шаг до размещения вашего проекта в сети.",
      "Homepage.githubBox.title.not-versioned": "Загрузите ваш проект на GitHub",
      "Homepage.githubBox.title.versioned": "Проект загружен на GitHub",
      "Homepage.subTitle": "Следуйте этим двум шагам, чтобы получить все необходимое для работы Strapi в продакшене.",
      "Homepage.textBox.label.not-versioned": "Зачем загружать мой проект на GitHub?",
      "Homepage.textBox.label.versioned": "Попробуйте Strapi Cloud бесплатно!",
      "Homepage.textBox.text.not-versioned": "Strapi Cloud загружает и развертывает ваш проект из репозитория GitHub. Это лучший способ версионирования, управления и развертывания вашего проекта. Следуйте инструкциям на GitHub для успешной загрузки.",
      "Homepage.textBox.text.versioned": "Strapi Cloud предлагает 14-дневный бесплатный пробный период, позволяя вам протестировать ваш проект в облаке со всеми функциями.",
      "Homepage.title": "Полностью управляемый облачный хостинг для вашего проекта Strapi",
      "Media Library": "Медиатека",
      "New entry": "Новая запись",
      "Password": "Пароль",
      "Plugin.name": "Развертывание",
      "Provider": "Провайдер",
      "ResetPasswordToken": "Токен сброса пароля",
      "Role": "Роль",
      "Roles & Permissions": "Роли и разрешения",
      "Roles.ListPage.notification.delete-all-not-allowed": "Некоторые роли не могут быть удалены, так как они связаны с пользователями",
      "Roles.ListPage.notification.delete-not-allowed": "Роль нельзя удалить, если она связана с пользователями",
      "Roles.RoleRow.select-all": "Выбрать {name} для массовых действий",
      "Roles.RoleRow.user-count": "{number, plural, =0 {# пользователь} one {# пользователь} other {# пользователей}}",
      "Roles.components.List.empty.withSearch": "Нет ролей, соответствующих запросу ({search})...",
      "Settings.PageTitle": "Настройки - {name}",
      "Settings.apiTokens.addFirstToken": "Добавьте ваш первый API-токен",
      "Settings.apiTokens.addNewToken": "Добавить новый API-токен",
      "Settings.apiTokens.copy.editMessage": "Из соображений безопасности вы можете увидеть ваш токен только один раз.",
      "Settings.apiTokens.copy.editTitle": "Этот токен больше недоступен.",
      "Settings.apiTokens.copy.lastWarning": "Обязательно скопируйте этот токен, вы не сможете увидеть его снова!",
      "Settings.apiTokens.create": "Создать новый API-токен",
      "Settings.apiTokens.description": "Список сгенерированных токенов для использования API",
      "Settings.apiTokens.emptyStateLayout": "У вас пока нет контента...",
      "Settings.apiTokens.notification.copied": "Токен скопирован в буфер обмена.",
      "Settings.apiTokens.title": "API-токены",
      "Settings.apiTokens.types.full-access": "Полный доступ",
      "Settings.apiTokens.types.read-only": "Только чтение",
      "Settings.application.customization": "Настройка",
      "Settings.application.customization.carousel-hint": "Измените логотип админ-панели (Максимальные размеры: {dimension}x{dimension}, Максимальный размер файла: {size}KB)",
      "Settings.application.customization.carousel-slide.label": "Слайд с логотипом",
      "Settings.application.customization.carousel.change-action": "Изменить логотип",
      "Settings.application.customization.carousel.reset-action": "Сбросить логотип",
      "Settings.application.customization.carousel.title": "Логотип",
      "Settings.application.customization.modal.cancel": "Отмена",
      "Settings.application.customization.modal.pending": "Ожидание логотипа",
      "Settings.application.customization.modal.pending.card-badge": "изображение",
      "Settings.application.customization.modal.pending.choose-another": "Выбрать другой логотип",
      "Settings.application.customization.modal.pending.subtitle": "Управляйте выбранным логотипом перед загрузкой",
      "Settings.application.customization.modal.pending.title": "Логотип готов к загрузке",
      "Settings.application.customization.modal.pending.upload": "Загрузить логотип",
      "Settings.application.customization.modal.tab.label": "Как вы хотите загрузить свои файлы?",
      "Settings.application.customization.modal.upload": "Загрузить логотип",
      "Settings.application.customization.modal.upload.cta.browse": "Выбрать файлы",
      "Settings.application.customization.modal.upload.drag-drop": "Перетащите сюда или",
      "Settings.application.customization.modal.upload.error-format": "Неверный формат файла (разрешены только: jpeg, jpg, png, svg).",
      "Settings.application.customization.modal.upload.error-network": "Ошибка сети",
      "Settings.application.customization.modal.upload.error-size": "Загруженный файл слишком большой (максимальные размеры: {dimension}x{dimension}, максимальный размер файла: {size}KB)",
      "Settings.application.customization.modal.upload.file-validation": "Макс. размер: {dimension}x{dimension}, Макс. вес файла: {size}KB",
      "Settings.application.customization.modal.upload.from-computer": "С компьютера",
      "Settings.application.customization.modal.upload.from-url": "По URL",
      "Settings.application.customization.modal.upload.from-url.input-label": "URL",
      "Settings.application.customization.modal.upload.next": "Далее",
      "Settings.application.description": "Глобальная информация админ-панели",
      "Settings.application.edition-title": "Текущий тариф",
      "Settings.application.get-help": "Получить помощь",
      "Settings.application.link-pricing": "Посмотреть все тарифные планы",
      "Settings.application.link-upgrade": "Обновить админ-панель",
      "Settings.application.node-version": "Версия Node.js",
      "Settings.application.strapi-version": "Версия Strapi",
      "Settings.application.strapiVersion": "Версия Strapi",
      "Settings.application.title": "Обзор",
      "Settings.error": "Ошибка",
      "Settings.global": "Глобальные настройки",
      "Settings.permissions": "Админ-панель",
      "Settings.permissions.category": "Настройки прав для {category}",
      "Settings.permissions.category.plugins": "Настройки прав для плагина {category}",
      "Settings.permissions.conditions.anytime": "В любое время",
      "Settings.permissions.conditions.apply": "Применить",
      "Settings.permissions.conditions.can": "Можно",
      "Settings.permissions.conditions.define-conditions": "Определить условия",
      "Settings.permissions.conditions.links": "Ссылки",
      "Settings.permissions.conditions.no-actions": "Сначала выберите действия (создание, чтение, обновление и т. д.), прежде чем задавать для них условия.",
      "Settings.permissions.conditions.none-selected": "В любое время",
      "Settings.permissions.conditions.or": "ИЛИ",
      "Settings.permissions.conditions.when": "Когда",
      "Settings.permissions.select-all-by-permission": "Выбрать все права {label}",
      "Settings.permissions.select-by-permission": "Выбрать право {label}",
      "Settings.permissions.users.create": "Пригласить нового пользователя",
      "Settings.permissions.users.form.email": "Email",
      "Settings.permissions.users.form.firstname": "Имя",
      "Settings.permissions.users.form.lastname": "Фамилия",
      "Settings.permissions.users.form.sso": "Подключиться через SSO",
      "Settings.permissions.users.form.sso.description": "Если включено (ON), пользователи могут войти через SSO",
      "Settings.permissions.users.listview.header.subtitle": "Все пользователи, имеющие доступ к админ-панели Strapi",
      "Settings.permissions.users.tabs.label": "Разрешения вкладок",
      "Settings.profile.form.notify.data.loaded": "Данные вашего профиля загружены",
      "Settings.profile.form.section.experience.clear.select": "Очистить выбранный язык интерфейса",
      "Settings.profile.form.section.experience.here": "здесь",
      "Settings.profile.form.section.experience.interfaceLanguage": "Язык интерфейса",
      "Settings.profile.form.section.experience.interfaceLanguage.hint": "Это изменит отображение интерфейса только для вас.",
      "Settings.profile.form.section.experience.interfaceLanguageHelp": "Изменения предпочтений применяются только к вам. Подробнее {here}.",
      "Settings.profile.form.section.experience.mode.hint": "Отображает интерфейс в выбранном режиме.",
      "Settings.profile.form.section.experience.mode.label": "Режим интерфейса",
      "Settings.profile.form.section.experience.mode.option-label": "Режим {name}",
      "Settings.profile.form.section.experience.title": "Опыт работы",
      "Settings.profile.form.section.helmet.title": "Профиль пользователя",
      "Settings.profile.form.section.profile.page.title": "Страница профиля",
      "Settings.roles.create.description": "Определите права, предоставляемые роли",
      "Settings.roles.create.title": "Создать роль",
      "Settings.roles.created": "Роль создана",
      "Settings.roles.edit.title": "Редактировать роль",
      "Settings.roles.form.button.users-with-role": "{number, plural, =0 {# пользователей} one {# пользователь} other {# пользователей}} с этой ролью",
      "Settings.roles.form.created": "Создано",
      "Settings.roles.form.description": "Название и описание роли",
      "Settings.roles.form.permission.property-label": "Права {label}",
      "Settings.roles.form.permissions.attributesPermissions": "Права на поля",
      "Settings.roles.form.permissions.create": "Создать",
      "Settings.roles.form.permissions.delete": "Удалить",
      "Settings.roles.form.permissions.publish": "Опубликовать",
      "Settings.roles.form.permissions.read": "Читать",
      "Settings.roles.form.permissions.update": "Обновить",
      "Settings.roles.list.button.add": "Добавить новую роль",
      "Settings.roles.list.description": "Список ролей",
      "Settings.roles.title.singular": "роль",
      "Settings.sso.description": "Настроить параметры единого входа (SSO).",
      "Settings.sso.form.defaultRole.description": "Новая учетная запись будет автоматически привязана к выбранной роли",
      "Settings.sso.form.defaultRole.description-not-allowed": "У вас нет разрешения на просмотр администраторских ролей",
      "Settings.sso.form.defaultRole.label": "Роль по умолчанию",
      "Settings.sso.form.registration.description": "Создать нового пользователя при входе через SSO, если аккаунт отсутствует",
      "Settings.sso.form.registration.label": "Автоматическая регистрация",
      "Settings.sso.title": "Единый вход (SSO)",
      "Settings.webhooks.create": "Создать вебхук",
      "Settings.webhooks.create.header": "Создать новый заголовок",
      "Settings.webhooks.created": "Вебхук создан",
      "Settings.webhooks.event.publish-tooltip": "Это событие доступно только для контента с включенной системой черновиков/публикации",
      "Settings.webhooks.events.create": "Создать",
      "Settings.webhooks.events.update": "Обновить",
      "Settings.webhooks.form.events": "События",
      "Settings.webhooks.form.headers": "Заголовки",
      "Settings.webhooks.form.url": "URL",
      "Settings.webhooks.headers.remove": "Удалить строку заголовка {number}",
      "Settings.webhooks.key": "Ключ",
      "Settings.webhooks.list.button.add": "Создать новый вебхук",
      "Settings.webhooks.list.description": "Получать уведомления о изменениях через POST-запросы",
      "Settings.webhooks.list.empty.description": "Вебхуки не найдены",
      "Settings.webhooks.list.empty.link": "Смотрите нашу документацию",
      "Settings.webhooks.list.empty.title": "Вебхуков пока нет",
      "Settings.webhooks.list.th.actions": "Действия",
      "Settings.webhooks.list.th.status": "Статус",
      "Settings.webhooks.singular": "вебхук",
      "Settings.webhooks.title": "Вебхуки",
      "Settings.webhooks.to.delete": "{webhooksToDeleteLength, plural, one {# элемент} other {# элементов}} выбрано",
      "Settings.webhooks.trigger": "Триггер",
      "Settings.webhooks.trigger.cancel": "Отменить триггер",
      "Settings.webhooks.trigger.pending": "Ожидание...",
      "Settings.webhooks.trigger.save": "Сохраните для запуска триггера",
      "Settings.webhooks.trigger.success": "Успешно!",
      "Settings.webhooks.trigger.success.label": "Триггер сработал успешно",
      "Settings.webhooks.trigger.test": "Тестовый триггер",
      "Settings.webhooks.trigger.title": "Сохраните перед запуском триггера",
      "Settings.webhooks.value": "Значение",
      "Usecase.back-end": "Back-end разработчик",
      "Usecase.button.skip": "Пропустить этот вопрос",
      "Usecase.content-creator": "Создатель контента",
      "Usecase.front-end": "Front-end разработчик",
      "Usecase.full-stack": "Full-stack разработчик",
      "Usecase.input.work-type": "Какой вид работы вы выполняете?",
      "Usecase.notification.success.project-created": "Проект успешно создан",
      "Usecase.other": "Другое",
      "Usecase.title": "Расскажите немного о себе",
      "Username": "Имя пользователя",
      "Users": "Пользователи",
      "Users & Permissions": "Пользователи и разрешения",
      "Users.components.List.empty": "Пользователей нет...",
      "Users.components.List.empty.withFilters": "Нет пользователей, соответствующих примененным фильтрам...",
      "Users.components.List.empty.withSearch": "Нет пользователей, соответствующих запросу ({search})...",
      "admin.pages.MarketPlacePage.helmet": "Маркетплейс - Плагины",
      "admin.pages.MarketPlacePage.missingPlugin.description": "Расскажите, какой плагин вам нужен, и мы уведомим разработчиков из сообщества Strapi, если им потребуется вдохновение!",
      "admin.pages.MarketPlacePage.missingPlugin.title": "Не хватает плагина?",
      "admin.pages.MarketPlacePage.offline.subtitle": "Для доступа к Strapi Market необходимо подключение к интернету.",
      "admin.pages.MarketPlacePage.offline.title": "Вы офлайн",
      "admin.pages.MarketPlacePage.plugin.copy": "Скопировать команду установки",
      "admin.pages.MarketPlacePage.plugin.copy.success": "Команда установки готова к вставке в терминал",
      "admin.pages.MarketPlacePage.plugin.info": "Подробнее",
      "admin.pages.MarketPlacePage.plugin.info.label": "Подробнее о {pluginName}",
      "admin.pages.MarketPlacePage.plugin.info.text": "Узнать больше",
      "admin.pages.MarketPlacePage.plugin.installed": "Установлено",
      "admin.pages.MarketPlacePage.plugin.tooltip.madeByStrapi": "Разработано Strapi",
      "admin.pages.MarketPlacePage.plugin.tooltip.verified": "Плагин проверен Strapi",
      "admin.pages.MarketPlacePage.plugins": "Плагины",
      "admin.pages.MarketPlacePage.providers": "Провайдеры",
      "admin.pages.MarketPlacePage.search.clear": "Очистить поиск",
      "admin.pages.MarketPlacePage.search.empty": "Нет результатов для \"{target}\"",
      "admin.pages.MarketPlacePage.search.placeholder": "Поиск",
      "admin.pages.MarketPlacePage.submit.plugin.link": "Предложить плагин",
      "admin.pages.MarketPlacePage.submit.provider.link": "Предложить провайдера",
      "admin.pages.MarketPlacePage.subtitle": "Расширьте возможности Strapi",
      "admin.pages.MarketPlacePage.tab-group.label": "Плагины и провайдеры для Strapi",
      "anErrorOccurred": "Упс! Что-то пошло не так. Попробуйте еще раз.",
      "apiError.FileTooBig": "Загруженный файл превышает максимально допустимый размер.",
      "app.component.CopyToClipboard.label": "Скопировать в буфер обмена",
      "app.component.search.label": "Поиск {target}",
      "app.component.table.duplicate": "Дублировать {target}",
      "app.component.table.edit": "Редактировать {target}",
      "app.component.table.select.one-entry": "Выбрать {target}",
      "app.components.BlockLink.blog": "Блог",
      "app.components.BlockLink.blog.content": "Читайте последние новости о Strapi и его экосистеме.",
      "app.components.BlockLink.cloud": "Strapi Cloud",
      "app.components.BlockLink.cloud.content": "Полностью управляемый облачный хостинг для вашего проекта Strapi.",
      "app.components.BlockLink.code": "Примеры кода",
      "app.components.BlockLink.code.content": "Учитесь, тестируя реальные проекты, разработанные сообществом.",
      "app.components.BlockLink.documentation.content": "Ознакомьтесь с основными концепциями, руководствами и инструкциями.",
      "app.components.BlockLink.tutorial": "Учебные материалы",
      "app.components.BlockLink.tutorial.content": "Следуйте пошаговым инструкциям по использованию и настройке Strapi.",
      "app.components.Button.cancel": "Отмена",
      "app.components.Button.confirm": "Подтвердить",
      "app.components.Button.reset": "Сбросить",
      "app.components.ComingSoonPage.comingSoon": "Скоро",
      "app.components.ConfirmDialog.title": "Подтверждение",
      "app.components.DownloadInfo.download": "Загрузка...",
      "app.components.DownloadInfo.text": "Это может занять некоторое время. Спасибо за ваше терпение.",
      "app.components.EmptyAttributes.title": "Поля отсутствуют",
      "app.components.EmptyStateLayout.content-document": "Контент не найден",
      "app.components.EmptyStateLayout.content-permissions": "У вас нет прав на доступ к этому контенту",
      "app.components.GuidedTour.CM.create.content": "<p>Создавайте и управляйте всем контентом в Контент-менеджере.</p><p>Например, для блога можно написать статью, сохранить и опубликовать её.</p><p>💡 Быстрый совет - не забудьте нажать кнопку публикации.</p>",
      "app.components.GuidedTour.CM.create.title": "⚡️ Создайте контент",
      "app.components.GuidedTour.CM.success.content": "<p>Отлично, еще один шаг!</p><b>🚀  Посмотрите контент в действии</b>",
      "app.components.GuidedTour.CM.success.cta.title": "Протестировать API",
      "app.components.GuidedTour.CM.success.title": "Шаг 2: Завершено ✅",
      "app.components.GuidedTour.CTB.create.content": "<p>Коллекционные типы позволяют управлять несколькими записями, а одиночные — одной записью.</p><p>Например, в блоге статьи будут коллекционным типом, а главная страница — одиночным.</p>",
      "app.components.GuidedTour.CTB.create.cta.title": "Создать коллекционный тип",
      "app.components.GuidedTour.CTB.create.title": "🧠 Создайте первую коллекцию",
      "app.components.GuidedTour.CTB.success.content": "<p>Хорошая работа!</p><b>⚡️ Что вы хотите рассказать миру?</b>",
      "app.components.GuidedTour.CTB.success.title": "Шаг 1: Завершено ✅",
      "app.components.GuidedTour.apiTokens.create.content": "<p>Сгенерируйте токен аутентификации и получите доступ к созданному контенту.</p>",
      "app.components.GuidedTour.apiTokens.create.cta.title": "Создать API-токен",
      "app.components.GuidedTour.apiTokens.create.title": "🚀 Посмотрите контент в действии",
      "app.components.GuidedTour.apiTokens.success.content": "<p>Проверьте контент, сделав HTTP-запрос:</p><ul><li><p>К этому URL: <light>https://'<'ВАШ_ДОМЕН'>'/api/'<'ВАШ_КТ'>'</light></p></li><li><p>С заголовком: <light>Authorization: bearer '<'ВАШ_API_ТОКЕН'>'</light></p></li></ul>",
      "app.components.GuidedTour.apiTokens.success.cta.title": "Вернуться на главную",
      "app.components.GuidedTour.apiTokens.success.title": "Шаг 3: Завершено ✅",
      "app.components.GuidedTour.create-content": "Создать контент",
      "app.components.GuidedTour.home.CM.title": "⚡️ Что вы хотите поделиться с миром?",
      "app.components.GuidedTour.home.CTB.cta.title": "Перейти в Конструктор типов контента",
      "app.components.GuidedTour.home.CTB.title": "🧠 Постройте структуру контента",
      "app.components.GuidedTour.home.apiTokens.cta.title": "Протестировать API",
      "app.components.GuidedTour.skip": "Пропустить тур",
      "app.components.GuidedTour.title": "3 шага для начала",
      "app.components.HomePage.button.blog": "Подробнее в блоге",
      "app.components.HomePage.community": "Присоединяйтесь к сообществу",
      "app.components.HomePage.community.content": "Обсуждайте с членами команды, участниками и разработчиками на разных платформах.",
      "app.components.HomePage.create": "Создайте свой первый тип контента",
      "app.components.HomePage.roadmap": "Посмотрите наш план развития",
      "app.components.HomePage.welcome": "Добро пожаловать 👋",
      "app.components.HomePage.welcome.again": "С возвращением 👋",
      "app.components.HomePage.welcomeBlock.content": "Поздравляем! Вы вошли как первый администратор. Чтобы открыть мощные возможности Strapi, мы рекомендуем создать ваш первый тип контента!",
      "app.components.HomePage.welcomeBlock.content.again": "Мы надеемся, что вы продвигаетесь в своем проекте! Читайте последние новости о Strapi. Мы стараемся улучшить продукт на основе ваших отзывов.",
      "app.components.HomePage.welcomeBlock.content.issues": "проблемы.",
      "app.components.HomePage.welcomeBlock.content.raise": " или создайте ",
      "app.components.ImgPreview.hint": "Перетащите файл в эту область или {browse}, чтобы загрузить",
      "app.components.ImgPreview.hint.browse": "выберите",
      "app.components.InputFile.newFile": "Добавить новый файл",
      "app.components.InputFileDetails.open": "Открыть в новой вкладке",
      "app.components.InputFileDetails.originalName": "Оригинальное имя:",
      "app.components.InputFileDetails.remove": "Удалить этот файл",
      "app.components.InputFileDetails.size": "Размер:",
      "app.components.InstallPluginPage.Download.description": "Загрузка и установка плагина может занять несколько секунд.",
      "app.components.InstallPluginPage.Download.title": "Загрузка...",
      "app.components.InstallPluginPage.description": "Расширьте возможности вашего приложения без усилий.",
      "app.components.LeftMenu.collapse": "Свернуть навигацию",
      "app.components.LeftMenu.expand": "Развернуть навигацию",
      "app.components.LeftMenu.general": "Общее",
      "app.components.LeftMenu.logo.alt": "Логотип приложения",
      "app.components.LeftMenu.logout": "Выйти",
      "app.components.LeftMenu.navbrand.title": "Панель управления Strapi",
      "app.components.LeftMenu.navbrand.workplace": "Рабочая область",
      "app.components.LeftMenu.plugins": "Плагины",
      "app.components.LeftMenuFooter.help": "Помощь",
      "app.components.LeftMenuFooter.poweredBy": "Работает на ",
      "app.components.LeftMenuLinkContainer.collectionTypes": "Коллекционные типы",
      "app.components.LeftMenuLinkContainer.configuration": "Конфигурации",
      "app.components.LeftMenuLinkContainer.general": "Общее",
      "app.components.LeftMenuLinkContainer.noPluginsInstalled": "Плагины еще не установлены",
      "app.components.LeftMenuLinkContainer.plugins": "Плагины",
      "app.components.LeftMenuLinkContainer.singleTypes": "Одиночные типы",
      "app.components.ListPluginsPage.deletePlugin.description": "Удаление плагина может занять несколько секунд.",
      "app.components.ListPluginsPage.deletePlugin.title": "Удаление",
      "app.components.ListPluginsPage.description": "Список установленных плагинов в проекте.",
      "app.components.ListPluginsPage.helmet.title": "Список плагинов",
      "app.components.Logout.logout": "Выйти",
      "app.components.Logout.profile": "Профиль",
      "app.components.MarketplaceBanner": "Откройте для себя плагины, созданные сообществом, и многое другое, чтобы ускорить запуск вашего проекта, на Strapi Awesome.",
      "app.components.MarketplaceBanner.image.alt": "Логотип ракеты Strapi",
      "app.components.MarketplaceBanner.link": "Посмотрите прямо сейчас",
      "app.components.NotFoundPage.back": "Вернуться на главную",
      "app.components.NotFoundPage.description": "Страница не найдена",
      "app.components.Official": "Официальный",
      "app.components.Onboarding.help.button": "Кнопка помощи",
      "app.components.Onboarding.label.completed": "% завершено",
      "app.components.Onboarding.title": "Обучающие видео",
      "app.components.PluginCard.Button.label.download": "Загрузить",
      "app.components.PluginCard.Button.label.install": "Уже установлено",
      "app.components.PluginCard.PopUpWarning.install.impossible.autoReload.needed": "Функция autoReload должна быть включена. Пожалуйста, запустите приложение с `yarn develop`.",
      "app.components.PluginCard.PopUpWarning.install.impossible.confirm": "Я понимаю!",
      "app.components.PluginCard.PopUpWarning.install.impossible.environment": "Из соображений безопасности плагин можно загружать только в среде разработки.",
      "app.components.PluginCard.PopUpWarning.install.impossible.title": "Загрузка невозможна",
      "app.components.PluginCard.compatible": "Совместим с вашим приложением",
      "app.components.PluginCard.compatibleCommunity": "Совместим с сообществом",
      "app.components.PluginCard.more-details": "Подробнее",
      "app.components.ToggleCheckbox.off-label": "False",
      "app.components.ToggleCheckbox.on-label": "True",
      "app.components.UpgradePlanModal.button": "Узнать больше",
      "app.components.UpgradePlanModal.limit-reached": "Вы достигли лимита",
      "app.components.UpgradePlanModal.text-ce": "Community Edition",
      "app.components.UpgradePlanModal.text-ee": "Enterprise Edition",
      "app.components.UpgradePlanModal.text-power": "Разблокируйте весь потенциал Strapi, обновив план до Enterprise Edition",
      "app.components.UpgradePlanModal.text-strapi": "Strapi, обновив ваш план до",
      "app.components.Users.MagicLink.connect": "Скопируйте и поделитесь этой ссылкой, чтобы предоставить доступ этому пользователю",
      "app.components.Users.MagicLink.connect.sso": "Отправьте эту ссылку пользователю, первый вход можно выполнить через провайдера SSO",
      "app.components.Users.ModalCreateBody.block-title.details": "Данные пользователя",
      "app.components.Users.ModalCreateBody.block-title.roles": "Роли пользователя",
      "app.components.Users.ModalCreateBody.block-title.roles.description": "Пользователь может иметь одну или несколько ролей",
      "app.components.Users.SortPicker.button-label": "Сортировать по",
      "app.components.Users.SortPicker.sortby.email_asc": "Email (А–Я)",
      "app.components.Users.SortPicker.sortby.email_desc": "Email (Я–А)",
      "app.components.Users.SortPicker.sortby.firstname_asc": "Имя (А–Я)",
      "app.components.Users.SortPicker.sortby.firstname_desc": "Имя (Я–А)",
      "app.components.Users.SortPicker.sortby.lastname_asc": "Фамилия (А–Я)",
      "app.components.Users.SortPicker.sortby.lastname_desc": "Фамилия (Я–А)",
      "app.components.Users.SortPicker.sortby.username_asc": "Имя пользователя (А–Я)",
      "app.components.Users.SortPicker.sortby.username_desc": "Имя пользователя (Я–А)",
      "app.components.listPlugins.button": "Добавить новый плагин",
      "app.components.listPlugins.title.none": "Плагины не установлены",
      "app.components.listPluginsPage.deletePlugin.error": "Произошла ошибка при удалении плагина",
      "app.containers.App.notification.error.init": "Произошла ошибка при запросе API",
      "app.containers.AuthPage.ForgotPasswordSuccess.text.contact-admin": "Если вы не получили ссылку, свяжитесь с администратором.",
      "app.containers.AuthPage.ForgotPasswordSuccess.text.email": "Получение ссылки для восстановления пароля может занять несколько минут.",
      "app.containers.AuthPage.ForgotPasswordSuccess.title": "Email отправлен",
      "app.containers.Users.EditPage.form.active.label": "Активный",
      "app.containers.Users.EditPage.header.label": "Редактировать {name}",
      "app.containers.Users.EditPage.header.label-loading": "Редактирование пользователя",
      "app.containers.Users.EditPage.roles-bloc-title": "Назначенные роли",
      "app.containers.Users.ModalForm.footer.button-success": "Пригласить пользователя",
      "app.links.configure-view": "Настроить отображение",
      "app.page.not.found": "Упс! Не удается найти страницу, которую вы ищете...",
      "app.static.links.cheatsheet": "Шпаргалка",
      "app.utils.SelectOption.defaultMessage": " ",
      "app.utils.add-filter": "Добавить фильтр",
      "app.utils.close-label": "Закрыть",
      "app.utils.defaultMessage": " ",
      "app.utils.duplicate": "Дублировать",
      "app.utils.edit": "Редактировать",
      "app.utils.errors.file-too-big.message": "Файл слишком большой",
      "app.utils.filter-value": "Значение фильтра",
      "app.utils.filters": "Фильтры",
      "app.utils.notify.data-loaded": "{target} загружен",
      "app.utils.placeholder.defaultMessage": " ",
      "app.utils.publish": "Опубликовать",
      "app.utils.select-all": "Выбрать все",
      "app.utils.select-field": "Выбрать поле",
      "app.utils.select-filter": "Выбрать фильтр",
      "app.utils.unpublish": "Снять с публикации",
      "bulk.select.label": "Выбрать все ресурсы",
      "button.next": "Далее",
      "checkControl.crop-duplicate": "Дублировать и обрезать ресурс",
      "checkControl.crop-original": "Обрезать оригинальный ресурс",
      "clearLabel": "Очистить",
      "coming.soon": "Этот контент в настоящее время в разработке и вернется через несколько недель!",
      "component.Input.error.validation.integer": "Значение должно быть целым числом",
      "components.AutoReloadBlocker.description": "Запустите Strapi с одной из следующих команд:",
      "components.AutoReloadBlocker.header": "Для этого плагина требуется функция перезагрузки.",
      "components.ErrorBoundary.title": "Что-то пошло не так...",
      "components.FilterOptions.FILTER_TYPES.$contains": "содержит (с учетом регистра)",
      "components.FilterOptions.FILTER_TYPES.$endsWith": "заканчивается на",
      "components.FilterOptions.FILTER_TYPES.$eq": "равно",
      "components.FilterOptions.FILTER_TYPES.$gt": "больше чем",
      "components.FilterOptions.FILTER_TYPES.$gte": "больше или равно",
      "components.FilterOptions.FILTER_TYPES.$lt": "меньше чем",
      "components.FilterOptions.FILTER_TYPES.$lte": "меньше или равно",
      "components.FilterOptions.FILTER_TYPES.$ne": "не равно",
      "components.FilterOptions.FILTER_TYPES.$notContains": "не содержит (с учетом регистра)",
      "components.FilterOptions.FILTER_TYPES.$notNull": "не null",
      "components.FilterOptions.FILTER_TYPES.$null": "является null",
      "components.FilterOptions.FILTER_TYPES.$startsWith": "начинается с",
      "components.Input.error.attribute.key.taken": "Это значение уже существует",
      "components.Input.error.attribute.sameKeyAndName": "Не может быть одинаковым",
      "components.Input.error.attribute.taken": "Это имя поля уже используется",
      "components.Input.error.contain.lowercase": "Пароль должен содержать хотя бы одну строчную букву",
      "components.Input.error.contain.number": "Пароль должен содержать хотя бы одну цифру",
      "components.Input.error.contain.uppercase": "Пароль должен содержать хотя бы одну заглавную букву",
      "components.Input.error.contentTypeName.taken": "Это имя уже используется",
      "components.Input.error.custom-error": "{errorMessage} ",
      "components.Input.error.password.noMatch": "Пароли не совпадают",
      "components.Input.error.validation.email": "Неверный email",
      "components.Input.error.validation.json": "Не соответствует формату JSON",
      "components.Input.error.validation.lowercase": "Значение должно быть в нижнем регистре",
      "components.Input.error.validation.max": "Значение слишком велико.",
      "components.Input.error.validation.maxLength": "Значение слишком длинное.",
      "components.Input.error.validation.min": "Значение слишком мало.",
      "components.Input.error.validation.minLength": "Значение слишком короткое.",
      "components.Input.error.validation.minSupMax": "Не может быть больше максимального",
      "components.Input.error.validation.regex": "Значение не соответствует регулярному выражению.",
      "components.Input.error.validation.required": "Это поле обязательно.",
      "components.Input.error.validation.unique": "Это значение уже используется.",
      "components.InputSelect.option.placeholder": "Выберите здесь",
      "components.ListRow.empty": "Нет данных для отображения.",
      "components.NotAllowedInput.text": "Нет разрешения на просмотр этого поля",
      "components.OverlayBlocker.description": "Вы используете функцию, для которой требуется перезапуск сервера. Пожалуйста, подождите.",
      "components.OverlayBlocker.description.serverError": "Сервер должен был перезапуститься, проверьте логи в терминале.",
      "components.OverlayBlocker.title": "Ожидание перезапуска...",
      "components.OverlayBlocker.title.serverError": "Перезапуск занимает больше времени, чем ожидалось",
      "components.PageFooter.select": "Записей на странице",
      "components.ProductionBlocker.description": "Из соображений безопасности этот плагин отключен в других средах.",
      "components.ProductionBlocker.header": "Этот плагин доступен только в режиме разработки.",
      "components.Search.placeholder": "Поиск...",
      "components.TableHeader.sort": "Сортировать по {label}",
      "components.Wysiwyg.ToggleMode.markdown-mode": "Режим Markdown",
      "components.Wysiwyg.ToggleMode.preview-mode": "Режим предпросмотра",
      "components.Wysiwyg.collapse": "Свернуть",
      "components.Wysiwyg.selectOptions.H1": "Заголовок H1",
      "components.Wysiwyg.selectOptions.H2": "Заголовок H2",
      "components.Wysiwyg.selectOptions.H3": "Заголовок H3",
      "components.Wysiwyg.selectOptions.H4": "Заголовок H4",
      "components.Wysiwyg.selectOptions.H5": "Заголовок H5",
      "components.Wysiwyg.selectOptions.H6": "Заголовок H6",
      "components.Wysiwyg.selectOptions.title": "Добавить заголовок",
      "components.WysiwygBottomControls.charactersIndicators": "символов",
      "components.WysiwygBottomControls.fullscreen": "Развернуть",
      "components.WysiwygBottomControls.uploadFiles": "Перетащите файлы, вставьте из буфера обмена или {browse}.",
      "components.WysiwygBottomControls.uploadFiles.browse": "выберите их",
      "components.pagination.go-to": "Перейти на страницу {page}",
      "components.pagination.go-to-next": "Перейти на следующую страницу",
      "components.pagination.go-to-previous": "Перейти на предыдущую страницу",
      "components.pagination.remaining-links": "И еще {number} ссылок",
      "components.popUpWarning.button.cancel": "Нет, отменить",
      "components.popUpWarning.button.confirm": "Да, подтвердить",
      "components.popUpWarning.message": "Вы уверены, что хотите удалить это?",
      "components.popUpWarning.title": "Подтвердите действие",
      "content-manager.App.schemas.data-loaded": "Схемы успешно загружены",
      "content-manager.DynamicTable.relation-loaded": "Связи загружены",
      "content-manager.DynamicTable.relation-loading": "Загрузка связей",
      "content-manager.DynamicTable.relation-more": "Эта связь содержит больше сущностей, чем отображено",
      "content-manager.EditRelations.title": "Связанные данные",
      "content-manager.HeaderLayout.button.label-add-entry": "Создать новую запись",
      "content-manager.api.id": "API ID",
      "content-manager.apiError.This attribute must be unique": "{field} должно быть уникальным",
      "content-manager.components.AddFilterCTA.add": "Фильтры",
      "content-manager.components.AddFilterCTA.hide": "Фильтры",
      "content-manager.components.DragHandle-label": "Переместить",
      "content-manager.components.DraggableAttr.edit": "Нажмите для редактирования",
      "content-manager.components.DraggableCard.delete.field": "Удалить {item}",
      "content-manager.components.DraggableCard.edit.field": "Редактировать {item}",
      "content-manager.components.DraggableCard.move.field": "Переместить {item}",
      "content-manager.components.DynamicTable.row-line": "строка элемента {number}",
      "content-manager.components.DynamicZone.ComponentPicker-label": "Выберите компонент",
      "content-manager.components.DynamicZone.add-component": "Добавить компонент в {componentName}",
      "content-manager.components.DynamicZone.delete-label": "Удалить {name}",
      "content-manager.components.DynamicZone.error-message": "Компонент содержит ошибку(и)",
      "content-manager.components.DynamicZone.missing-components": "{number, plural, =0 {отсутствует # компонент(ов)} one {отсутствует # компонент} other {отсутствует # компонента}}",
      "content-manager.components.DynamicZone.move-down-label": "Переместить компонент вниз",
      "content-manager.components.DynamicZone.move-up-label": "Переместить компонент вверх",
      "content-manager.components.DynamicZone.pick-compo": "Выберите компонент",
      "content-manager.components.DynamicZone.required": "Компонент обязателен",
      "content-manager.components.EmptyAttributesBlock.button": "Перейти к настройкам",
      "content-manager.components.EmptyAttributesBlock.description": "Вы можете изменить настройки",
      "content-manager.components.FieldItem.linkToComponentLayout": "Настроить компоновку компонента",
      "content-manager.components.FieldSelect.label": "Добавить поле",
      "content-manager.components.FilterOptions.button.apply": "Применить",
      "content-manager.components.FiltersPickWrapper.PluginHeader.actions.apply": "Применить",
      "content-manager.components.FiltersPickWrapper.PluginHeader.actions.clearAll": "Очистить все",
      "content-manager.components.FiltersPickWrapper.PluginHeader.description": "Задайте условия для фильтрации записей",
      "content-manager.components.FiltersPickWrapper.PluginHeader.title.filter": "Фильтры",
      "content-manager.components.FiltersPickWrapper.hide": "Скрыть",
      "content-manager.components.LeftMenu.Search.label": "Поиск типа контента",
      "content-manager.components.LeftMenu.collection-types": "Коллекционные типы",
      "content-manager.components.LeftMenu.single-types": "Одиночные типы",
      "content-manager.components.LimitSelect.itemsPerPage": "Элементов на странице",
      "content-manager.components.NotAllowedInput.text": "Нет разрешения для просмотра этого поля",
      "content-manager.components.RepeatableComponent.error-message": "Компонент(ы) содержат ошибку(и)",
      "content-manager.components.Search.placeholder": "Поиск записи...",
      "content-manager.components.Select.draft-info-title": "Статус: Черновик",
      "content-manager.components.Select.publish-info-title": "Статус: Опубликовано",
      "content-manager.components.SettingsViewWrapper.pluginHeader.description.edit-settings": "Настройте, как будет выглядеть страница редактирования.",
      "content-manager.components.SettingsViewWrapper.pluginHeader.description.list-settings": "Определите настройки списка записей.",
      "content-manager.components.SettingsViewWrapper.pluginHeader.title": "Настроить вид - {name}",
      "content-manager.components.TableDelete.delete": "Удалить все",
      "content-manager.components.TableDelete.deleteSelected": "Удалить выбранные",
      "content-manager.components.TableDelete.label": "{number, plural, one {# запись} other {# записей}} выбрано",
      "content-manager.components.TableEmpty.withFilters": "Нет {contentType} с примененными фильтрами...",
      "content-manager.components.TableEmpty.withSearch": "Нет {contentType}, соответствующих запросу ({search})...",
      "content-manager.components.TableEmpty.withoutFilter": "Нет {contentType}...",
      "content-manager.components.empty-repeatable": "Записей пока нет. Нажмите кнопку ниже, чтобы добавить.",
      "content-manager.components.notification.info.maximum-requirement": "Вы уже достигли максимального количества полей",
      "content-manager.components.notification.info.minimum-requirement": "Добавлено поле для соответствия минимальным требованиям",
      "content-manager.components.repeatable.reorder.error": "Ошибка при изменении порядка полей компонента. Попробуйте еще раз",
      "content-manager.components.reset-entry": "Сбросить запись",
      "content-manager.components.uid.apply": "применить",
      "content-manager.components.uid.available": "Доступно",
      "content-manager.components.uid.regenerate": "Перегенерировать",
      "content-manager.components.uid.suggested": "предложено",
      "content-manager.components.uid.unavailable": "Недоступно",
      "content-manager.containers.Edit.Link.Layout": "Настроить компоновку",
      "content-manager.containers.Edit.Link.Model": "Редактировать коллекционный тип",
      "content-manager.containers.Edit.addAnItem": "Добавить элемент...",
      "content-manager.containers.Edit.clickToJump": "Нажмите, чтобы перейти к записи",
      "content-manager.containers.Edit.delete": "Удалить",
      "content-manager.containers.Edit.delete-entry": "Удалить эту запись",
      "content-manager.containers.Edit.editing": "Редактирование...",
      "content-manager.containers.Edit.information": "Информация",
      "content-manager.containers.Edit.information.by": "От",
      "content-manager.containers.Edit.information.created": "Создано",
      "content-manager.containers.Edit.information.draftVersion": "черновая версия",
      "content-manager.containers.Edit.information.editing": "Редактирование",
      "content-manager.containers.Edit.information.lastUpdate": "Последнее обновление",
      "content-manager.containers.Edit.information.publishedVersion": "опубликованная версия",
      "content-manager.containers.Edit.pluginHeader.title.new": "Создать запись",
      "content-manager.containers.Edit.reset": "Сбросить",
      "content-manager.containers.Edit.returnList": "Вернуться к списку",
      "content-manager.containers.Edit.seeDetails": "Детали",
      "content-manager.containers.Edit.submit": "Сохранить",
      "content-manager.containers.EditSettingsView.modal-form.edit-field": "Редактировать поле",
      "content-manager.containers.EditView.add.new-entry": "Добавить запись",
      "content-manager.containers.EditView.notification.errors": "Форма содержит ошибки",
      "content-manager.containers.Home.introduction": "Чтобы редактировать записи, перейдите по соответствующей ссылке в левом меню. Этот плагин пока не имеет полноценного интерфейса для редактирования настроек и находится в активной разработке.",
      "content-manager.containers.Home.pluginHeaderDescription": "Управляйте записями через мощный и удобный интерфейс.",
      "content-manager.containers.Home.pluginHeaderTitle": "Контент-менеджер",
      "content-manager.containers.List.draft": "Черновик",
      "content-manager.containers.List.errorFetchRecords": "Ошибка",
      "content-manager.containers.List.published": "Опубликовано",
      "content-manager.containers.ListPage.displayedFields": "Отображаемые поля",
      "content-manager.containers.ListPage.items": "{number, plural, =0 {записей} one {запись} other {записей}}",
      "content-manager.containers.ListPage.table-headers.published_at": "Статус",
      "content-manager.containers.ListSettingsView.modal-form.edit-label": "Редактировать {fieldName}",
      "content-manager.containers.SettingPage.add.field": "Добавить еще одно поле",
      "content-manager.containers.SettingPage.add.relational-field": "Добавить еще одно реляционное поле",
      "content-manager.containers.SettingPage.attributes": "Поля атрибутов",
      "content-manager.containers.SettingPage.attributes.description": "Определите порядок атрибутов",
      "content-manager.containers.SettingPage.editSettings.description": "Перетащите поля для настройки компоновки",
      "content-manager.containers.SettingPage.editSettings.entry.title": "Заголовок записи",
      "content-manager.containers.SettingPage.editSettings.entry.title.description": "Настройте отображаемое поле вашей записи",
      "content-manager.containers.SettingPage.editSettings.relation-field.description": "Задайте отображаемое поле в режимах редактирования и списка",
      "content-manager.containers.SettingPage.editSettings.title": "Редактирование (настройки)",
      "content-manager.containers.SettingPage.layout": "Компоновка",
      "content-manager.containers.SettingPage.listSettings.description": "Настроить параметры для этого типа коллекции",
      "content-manager.containers.SettingPage.listSettings.title": "Список (настройки)",
      "content-manager.containers.SettingPage.pluginHeaderDescription": "Настройка параметров для данного типа коллекции",
      "content-manager.containers.SettingPage.relations": "Реляционные поля",
      "content-manager.containers.SettingPage.settings": "Настройки",
      "content-manager.containers.SettingPage.view": "Вид",
      "content-manager.containers.SettingViewModel.pluginHeader.title": "Контент-менеджер - {name}",
      "content-manager.containers.SettingsPage.Block.contentType.description": "Настроить конкретные параметры",
      "content-manager.containers.SettingsPage.Block.contentType.title": "Типы коллекций",
      "content-manager.containers.SettingsPage.Block.generalSettings.description": "Настроить параметры по умолчанию для типов коллекций",
      "content-manager.containers.SettingsPage.Block.generalSettings.title": "Общие",
      "content-manager.containers.SettingsPage.pluginHeaderDescription": "Настроить параметры для всех типов коллекций и групп",
      "content-manager.containers.SettingsView.list.subtitle": "Настроить компоновку и отображение типов коллекций и групп",
      "content-manager.containers.SettingsView.list.title": "Конфигурация отображения",
      "content-manager.edit-settings-view.link-to-ctb.components": "Редактировать компонент",
      "content-manager.edit-settings-view.link-to-ctb.content-types": "Редактировать тип контента",
      "content-manager.emptyAttributes.button": "Перейти в конструктор типов коллекций",
      "content-manager.emptyAttributes.description": "Добавьте первое поле в ваш тип коллекции",
      "content-manager.emptyAttributes.title": "Полей пока нет",
      "content-manager.error.attribute.key.taken": "Это значение уже существует",
      "content-manager.error.attribute.sameKeyAndName": "Не могут быть одинаковыми",
      "content-manager.error.attribute.taken": "Это имя поля уже используется",
      "content-manager.error.contentTypeName.taken": "Это имя уже используется",
      "content-manager.error.model.fetch": "Произошла ошибка при загрузке конфигурации моделей.",
      "content-manager.error.record.create": "Произошла ошибка при создании записи.",
      "content-manager.error.record.delete": "Произошла ошибка при удалении записи.",
      "content-manager.error.record.fetch": "Произошла ошибка при загрузке записи.",
      "content-manager.error.record.update": "Произошла ошибка при обновлении записи.",
      "content-manager.error.records.count": "Произошла ошибка при получении количества записей.",
      "content-manager.error.records.fetch": "Произошла ошибка при загрузке записей.",
      "content-manager.error.schema.generation": "Произошла ошибка при генерации схемы.",
      "content-manager.error.validation.json": "Это не JSON",
      "content-manager.error.validation.max": "Значение слишком велико.",
      "content-manager.error.validation.maxLength": "Значение слишком длинное.",
      "content-manager.error.validation.min": "Значение слишком мало.",
      "content-manager.error.validation.minLength": "Значение слишком короткое.",
      "content-manager.error.validation.minSupMax": "Не может быть больше максимального",
      "content-manager.error.validation.regex": "Значение не соответствует регулярному выражению.",
      "content-manager.error.validation.required": "Это поле обязательно.",
      "content-manager.form.Input.bulkActions": "Включить массовые действия",
      "content-manager.form.Input.defaultSort": "Атрибут сортировки по умолчанию",
      "content-manager.form.Input.description": "Описание",
      "content-manager.form.Input.description.placeholder": "Отображаемое имя в профиле",
      "content-manager.form.Input.editable": "Редактируемое поле",
      "content-manager.form.Input.filters": "Включить фильтры",
      "content-manager.form.Input.label": "Метка",
      "content-manager.form.Input.label.inputDescription": "Это значение переопределяет метку, отображаемую в заголовке таблицы",
      "content-manager.form.Input.pageEntries": "Записей на странице",
      "content-manager.form.Input.pageEntries.inputDescription": "Примечание: Вы можете изменить это значение в настройках типа коллекции.",
      "content-manager.form.Input.placeholder": "Заполнитель",
      "content-manager.form.Input.placeholder.placeholder": "Мое потрясающее значение",
      "content-manager.form.Input.search": "Включить поиск",
      "content-manager.form.Input.search.field": "Включить поиск по этому полю",
      "content-manager.form.Input.sort.field": "Включить сортировку по этому полю",
      "content-manager.form.Input.sort.order": "Порядок сортировки по умолчанию",
      "content-manager.form.Input.wysiwyg": "Отображать как WYSIWYG",
      "content-manager.global.displayedFields": "Отображаемые поля",
      "content-manager.groups": "Группы",
      "content-manager.groups.numbered": "Группы ({number})",
      "content-manager.header.name": "Контент",
      "content-manager.link-to-ctb": "Редактировать модель",
      "content-manager.models": "Типы коллекций",
      "content-manager.models.numbered": "Типы коллекций ({number})",
      "content-manager.notification.error.displayedFields": "Необходимо хотя бы одно отображаемое поле",
      "content-manager.notification.error.relationship.fetch": "Произошла ошибка при получении связей.",
      "content-manager.notification.info.SettingPage.disableSort": "Необходимо, чтобы хотя бы один атрибут поддерживал сортировку",
      "content-manager.notification.info.minimumFields": "Необходимо отображать хотя бы одно поле",
      "content-manager.notification.upload.error": "Произошла ошибка при загрузке файлов",
      "content-manager.pageNotFound": "Страница не найдена",
      "content-manager.pages.ListView.header-subtitle": "{number, plural, =0 {# записей} one {# запись} other {# записей}} найдено",
      "content-manager.pages.NoContentType.button": "Создать первый тип контента",
      "content-manager.pages.NoContentType.text": "У вас еще нет контента, рекомендуем создать ваш первый тип контента.",
      "content-manager.permissions.not-allowed.create": "Вам запрещено создавать документы",
      "content-manager.permissions.not-allowed.update": "Вам запрещено просматривать этот документ",
      "content-manager.plugin.description.long": "Быстрый способ просмотра, редактирования и удаления данных в вашей базе данных.",
      "content-manager.plugin.description.short": "Быстрый способ просмотра, редактирования и удаления данных в вашей базе данных.",
      "content-manager.popUpWarning.bodyMessage.contentType.delete": "Вы уверены, что хотите удалить эту запись?",
      "content-manager.popUpWarning.bodyMessage.contentType.delete.all": "Вы уверены, что хотите удалить эти записи?",
      "content-manager.popUpWarning.warning.cancelAllSettings": "Вы уверены, что хотите отменить изменения?",
      "content-manager.popUpWarning.warning.publish-question": "Вы уверены, что хотите опубликовать?",
      "content-manager.popUpWarning.warning.unpublish": "Снятие с публикации изменит статус на черновик.",
      "content-manager.popUpWarning.warning.unpublish-question": "Вы уверены, что хотите снять с публикации?",
      "content-manager.popUpWarning.warning.updateAllSettings": "Это изменит все ваши настройки",
      "content-manager.popUpwarning.warning.has-draft-relations.button-confirm": "Да, опубликовать",
      "content-manager.popUpwarning.warning.has-draft-relations.message": "<b>{count, plural, =0 { из ваших связей не опубликована} one { из ваших связей не опубликована} other { из ваших связей не опубликованы}}</b>.<br></br>Это может привести к ошибкам и разорванным ссылкам в вашем проекте.",
      "content-manager.popover.display-relations.label": "Показать связи",
      "content-manager.select.currently.selected": "{count} выбрано",
      "content-manager.success.record.delete": "Удалено",
      "content-manager.success.record.publish": "Опубликовано",
      "content-manager.success.record.save": "Сохранено",
      "content-manager.success.record.unpublish": "Снято с публикации",
      "content-manager.utils.data-loaded": "{number, plural, =1 {Запись успешно загружена} other {Записи успешно загружены}}",
      "content-manager.widget.last-edited.no-data": "Нет отредактированных записей",
      "content-manager.widget.last-edited.single-type": "Одиночный тип",
      "content-manager.widget.last-edited.title": "Последние отредактированные записи",
      "content-manager.widget.last-published.no-data": "Нет опубликованных записей",
      "content-manager.widget.last-published.title": "Последние опубликованные записи",
      "content.isLoading": "Контент загружается.",
      "control-card.add": "Добавить",
      "control-card.cancel": "Отмена",
      "control-card.copy-link": "Скопировать ссылку",
      "control-card.crop": "Обрезать",
      "control-card.download": "Скачать",
      "control-card.edit": "Редактировать",
      "control-card.replace-media": "Заменить медиафайл",
      "control-card.save": "Сохранить",
      "control-card.stop-crop": "Остановить обрезку",
      "dark": "Темная",
      "filter.add": "Добавить фильтр",
      "form.button.continue": "Продолжить",
      "form.button.done": "Готово",
      "form.button.replace-media": "Заменить медиафайл",
      "form.input.description.file-alt": "Этот текст будет отображаться, если ресурс не может быть показан.",
      "form.input.label.file-alt": "Альтернативный текст",
      "form.input.label.file-caption": "Подпись",
      "form.input.label.file-name": "Имя файла",
      "form.upload-url.error.url.invalid": "Один URL недействителен",
      "form.upload-url.error.url.invalids": "{number} URL недействительны",
      "global.actions": "Действия",
      "global.active": "Активный",
      "global.back": "Назад",
      "global.cancel": "Отмена",
      "global.change-password": "Сменить пароль",
      "global.content-manager": "Контент-менеджер",
      "global.continue": "Продолжить",
      "global.delete": "Удалить",
      "global.delete-target": "Удалить {target}",
      "global.description": "Описание",
      "global.details": "Детали",
      "global.disabled": "Отключено",
      "global.documentation": "Документация",
      "global.enabled": "Включено",
      "global.finish": "Завершить",
      "global.inactive": "Неактивный",
      "global.marketplace": "Маркетплейс",
      "global.name": "Имя",
      "global.none": "Нет",
      "global.password": "Пароль",
      "global.plugins": "Плагины",
      "global.plugins.content-manager": "Контент-менеджер",
      "global.plugins.content-manager.description": "Быстрый способ просмотра, редактирования и удаления данных в вашей базе данных.",
      "global.plugins.content-type-builder": "Конструктор типов контента",
      "global.plugins.content-type-builder.description": "Создавайте структуры данных для API, добавляйте новые поля и связи. Файлы автоматически создаются и обновляются в вашем проекте.",
      "global.plugins.documentation": "Документация",
      "global.plugins.documentation.description": "Создайте OpenAPI-документ и просматривайте ваш API через SWAGGER UI.",
      "global.plugins.email": "Email",
      "global.plugins.email.description": "Настройте отправку email-уведомлений.",
      "global.plugins.graphql": "GraphQL",
      "global.plugins.graphql.description": "Добавляет GraphQL-эндпоинт с базовыми методами API.",
      "global.plugins.i18n": "Интернационализация",
      "global.plugins.i18n.description": "Этот плагин позволяет создавать, читать и редактировать контент на разных языках как из панели администратора, так и через API.",
      "global.plugins.sentry": "Sentry",
      "global.plugins.sentry.description": "Отправляет события ошибок Strapi в Sentry.",
      "global.plugins.upload": "Медиатека",
      "global.plugins.upload.description": "Управление медиафайлами.",
      "global.plugins.users-permissions": "Роли и разрешения",
      "global.plugins.users-permissions.description": "Защитите ваш API с помощью полной системы аутентификации на основе JWT. Этот плагин также включает стратегию ACL, позволяющую управлять разрешениями пользователей.",
      "global.profile": "Профиль",
      "global.prompt.unsaved": "Вы уверены, что хотите покинуть страницу? Все несохраненные изменения будут потеряны",
      "global.reset-password": "Сброс пароля",
      "global.roles": "Роли",
      "global.save": "Сохранить",
      "global.search": "Поиск",
      "global.see-more": "Подробнее",
      "global.select": "Выбрать",
      "global.select-all-entries": "Выбрать все записи",
      "global.settings": "Настройки",
      "global.strapi-author": "Автор",
      "global.strapi-editor": "Редактор",
      "global.strapi-super-admin": "Суперадминистратор",
      "global.table.header.email": "Email",
      "global.table.header.firstname": "Имя",
      "global.table.header.isActive": "Статус пользователя",
      "global.table.header.lastname": "Фамилия",
      "global.table.header.roles": "Роли",
      "global.table.header.username": "Имя пользователя",
      "global.type": "Тип",
      "global.users": "Пользователи",
      "header.actions.add-assets": "Добавить новые ресурсы",
      "header.actions.add-assets.folder": "папку",
      "header.actions.add-folder": "Добавить новую папку",
      "header.actions.upload-assets": "Загрузить ресурсы",
      "header.actions.upload-new-asset": "Загрузить новый ресурс",
      "header.content.assets": "{numberFolders, plural, one {1 папка} other {# папки}} - {numberAssets, plural, one {1 ресурс} other {# ресурсов}}",
      "header.content.assets-empty": "Нет ресурсов",
      "input.button.label": "Выбрать файлы",
      "input.label": "Перетащите файлы сюда или",
      "input.label-bold": "Перетащите и отпустите",
      "input.label-normal": "чтобы загрузить или",
      "input.notification.not-supported": "Вы не можете загрузить этот тип файла. Разрешены только следующие форматы – {fileTypes}",
      "input.placeholder": "Нажмите, чтобы добавить ресурс, или перетащите файл в эту область",
      "input.placeholder.icon": "Перетащите ресурс в эту зону",
      "input.url.description": "Разделяйте URL-адреса переносом строки.",
      "input.url.label": "URL",
      "light": "Светлая",
      "list-assets-select": "Выбрать ресурс {name}",
      "list.asset.at.finished": "Ресурсы загружены.",
      "list.assets-empty.search": "Результатов не найдено",
      "list.assets-empty.subtitle": "Добавьте первый ресурс.",
      "list.assets-empty.title": "Ресурсов пока нет",
      "list.assets-empty.title-withSearch": "Нет элементов, соответствующих примененным фильтрам",
      "list.assets.empty": "Медиатека пуста",
      "list.assets.empty-upload": "Загрузите ваши первые ресурсы...",
      "list.assets.empty.no-permissions": "Нет разрешений для просмотра",
      "list.assets.loading-asset": "Загрузка предпросмотра для медиа: {path}",
      "list.assets.not-supported-content": "Предпросмотр недоступен",
      "list.assets.preview-asset": "Предпросмотр видео по пути {path}",
      "list.assets.selected": "{numberFolders, plural, one {1 папка} other {# папки}} - {numberAssets, plural, one {1 ресурс} other {# ресурсов}}",
      "list.assets.title": "Ресурсы ({count})",
      "list.assets.to-upload": "{number, plural, =0 {Нет ресурсов} one {1 ресурс} other {# ресурсов}} готово к загрузке",
      "list.assets.type-not-allowed": "Этот тип файла не разрешен.",
      "list.folder.edit": "Редактировать папку",
      "list.folder.select": "Выбрать папку {name}",
      "list.folder.subtitle": "{folderCount, plural, =0 {# папка} one {# папка} other {# папки}}, {filesCount, plural, =0 {# ресурс} one {# ресурс} other {# ресурсов}}",
      "list.folders.link-label": "Перейти в папку",
      "list.folders.title": "Папки ({count})",
      "mediaLibraryInput.actions.nextSlide": "Следующий слайд",
      "mediaLibraryInput.actions.previousSlide": "Предыдущий слайд",
      "mediaLibraryInput.placeholder": "Нажмите, чтобы добавить ресурс, или перетащите его в эту область",
      "mediaLibraryInput.slideCount": "{n} из {m} слайдов",
      "modal.file-details.date": "Дата",
      "modal.file-details.dimensions": "Размеры",
      "modal.file-details.extension": "Расширение",
      "modal.file-details.id": "ID ресурса",
      "modal.file-details.size": "Размер",
      "modal.folder.elements.count": "{folderCount} папки, {assetCount} ресурсы",
      "modal.folder.move.title": "Переместить элементы в",
      "modal.header.browse": "Загрузить ресурсы",
      "modal.header.file-detail": "Детали",
      "modal.header.go-back": "Назад",
      "modal.header.pending-assets": "Ожидающие ресурсы",
      "modal.header.select-files": "Выбранные файлы",
      "modal.move.success-label": "Элементы успешно перемещены",
      "modal.nav.browse": "обзор",
      "modal.nav.computer": "С компьютера",
      "modal.nav.selected": "выбрано",
      "modal.nav.url": "Из URL",
      "modal.remove.success-label": "Элементы успешно удалены.",
      "modal.selected-list.sub-header-subtitle": "Перетащите, чтобы изменить порядок ресурсов в поле",
      "modal.upload-list.footer.button": "Загрузить {number, plural, one {# ресурс} other {# ресурсов}} в библиотеку",
      "modal.upload-list.sub-header-subtitle": "Управляйте ресурсами перед добавлением их в медиатеку",
      "modal.upload-list.sub-header.button": "Добавить еще ресурсы",
      "modal.upload.cancelled": "Загрузка отменена вручную.",
      "notification.contentType.relations.conflict": "Тип контента имеет конфликтующие связи",
      "notification.default.title": "Информация:",
      "notification.error": "Произошла ошибка",
      "notification.error.layout": "Не удалось загрузить макет",
      "notification.form.error.fields": "Форма содержит ошибки",
      "notification.form.success.fields": "Изменения сохранены",
      "notification.link-copied": "Ссылка скопирована в буфер обмена",
      "notification.permission.not-allowed-read": "У вас нет доступа к этому документу",
      "notification.success.delete": "Элемент удален",
      "notification.success.saved": "Сохранено",
      "notification.success.title": "Успех:",
      "notification.version.update.message": "Доступна новая версия Strapi!",
      "notification.warning.404": "404 - Страница не найдена",
      "notification.warning.title": "Предупреждение:",
      "or": "ИЛИ",
      "page.title": "Настройки - Медиатека",
      "permissions.not-allowed.update": "У вас нет разрешения на редактирование этого файла.",
      "plugin.description.long": "Управление медиафайлами.",
      "plugin.description.short": "Управление медиафайлами.",
      "plugin.name": "Медиатека",
      "request.error.model.unknown": "Эта модель не существует",
      "search.clear.label": "Очистить поиск",
      "search.label": "Поиск ресурса",
      "search.placeholder": "например: первая собака на луне",
      "settings.blockTitle": "Управление ресурсами",
      "settings.form.autoOrientation.description": "При включении этой опции изображение будет автоматически повернуто в соответствии с тегом ориентации EXIF.",
      "settings.form.autoOrientation.label": "Автоориентация",
      "settings.form.responsiveDimensions.description": "При включении этой опции будут созданы несколько форматов (малый, средний и большой) загруженного ресурса.",
      "settings.form.responsiveDimensions.label": "Адаптивная загрузка",
      "settings.form.sizeOptimization.description": "При включении этой опции размер изображения будет уменьшен с незначительной потерей качества.",
      "settings.form.sizeOptimization.label": "Оптимизация размера",
      "settings.form.videoPreview.description": "Будет сгенерирован шестисекундный предпросмотр видео (GIF)",
      "settings.form.videoPreview.label": "Предпросмотр",
      "settings.header.label": "Медиатека",
      "skipToContent": "Перейти к контенту",
      "submit": "Отправить",
      "upload.generic-error": "Произошла ошибка при загрузке файла.",
      "widget.last-edited.no-data": "Нет отредактированных записей",
      "widget.last-edited.single-type": "Одиночный тип",
      "widget.last-edited.title": "Последние отредактированные записи",
      "widget.last-published.no-data": "Нет опубликованных записей",
      "widget.last-published.title": "Последние опубликованные записи"
    },
  },
  languageNativeNames: {
    ru: 'Русский',
  },
};

const bootstrap = (app) => {
  console.log(app);
};

export default {
  config,
  bootstrap,
};
